name: Deploy Documentation to Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

# Set least-privilege permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup GitHub Pages
        uses: actions/configure-pages@983d63b72ee22451590c221101955b40023b7ff9 # v5.0.0

      - name: Upload Docs Artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda996908d24 # v3.0.1
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164db5de86f4b16c8485e18474e7f8c4e1 # v4.0.5
